apiVersion: cpet.belastingdienst.nl/v1alpha1
kind: PaasConfig
metadata:
  name: paas-config
spec:
  clusterwide_argocd_namespace: asns
  argopermissions:
    resource_name: argocd
    default_policy: "role:tester"
    role: admin
    header: g, system:cluster-admins, role:admin
  capabilities:
    argocd:
      applicationset: argoas
      default_permissions:
        argo-service-argocd-application-controller:
          - monitoring-edit
        argo-service-applicationset-controller:
          - monitoring-edit
      extra_permissions:
        argo-service-argocd-application-controller:
          - admin
      quotas:
        clusterwide: false
        defaults:
          limits.cpu: "5"
          limits.memory: 4Gi
          requests.cpu: "1"
          requests.memory: 1Gi
          requests.storage: "0"
          thin.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
        min: {}
        max: {}
        ratio: 0
    tekton:
      applicationset: tektonas
      default_permissions:
        pipeline:
          - view
          - alert-routing-edit
      extra_permissions:
        pipeline:
          - admin
      quotas:
        clusterwide: true
        defaults:
          limits.cpu: "5"
          limits.memory: 8Gi
          requests.cpu: "1"
          requests.memory: 2Gi
          requests.storage: "100Gi"
          thin.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
        min:
          limits.cpu: "5"
          limits.memory: 4Gi
        max:
          requests.cpu: "1"
          requests.memory: 1Gi
        ratio: 10
    sso:
      applicationset: ssoas
      default_permissions: {}
      extra_permissions: {}
      quotas:
        clusterwide: false
        defaults:
          limits.cpu: "1"
          limits.memory: 512Mi
          requests.cpu: "100m"
          requests.memory: 128Mi
          requests.storage: "0"
          thin.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
        min: {}
        max: {}
        ratio: 0
    grafana:
      applicationset: grafanaas
      default_permissions: {}
      extra_permissions: {}
      quotas:
        clusterwide: false
        defaults:
          limits.cpu: "2"
          limits.memory: 2Gi
          requests.cpu: "500m"
          requests.memory: 512Mi
          requests.storage: "2Gi"
          thin.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
        min: {}
        max: {}
        ratio: 0
  debug: false
  decryptKeyPaths:
    - /tmp/paas-e2e/secrets/priv
  ldap:
    host: my-ldap-host
    port: 13
  managed_by_label: argocd.argoproj.io/manby
  requestor_label: o.lbl
  quota_label: q.lbl
  rolemappings:
    default:
      - admin
    viewer:
      - view
  whitelist:
    namespace: wlns
    name: wlname
  exclude_appset_name: whatever
