name: Build and add install.yaml to release
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  sbom:
    name: Generate and upload install.yaml
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Install kustomize
        run: make kustomize

      - name: Generate install.yaml
        run: make build-installer
        env:
          IMAGE_TAG: ${{ github.ref_name }}

      - name: Add install.yaml to release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: manifests/install.yaml
