name: Build and add install.yaml to release
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  sbom:
    name: Generate and upload install.yaml
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install kustomize
        run: make kustomize

      - name: Generate install.yaml
        run: make build-installer
        env:
          IMAGE_TAG: ${{ github.ref_name }}

      - name: Add install.yaml to release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: manifests/install.yaml
