name: Build add SBOM and LICENSES.md to release
on:
  release:
    types:
      - published

jobs:
  sbom:
    name: Generate and upload SBOM
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f # v4.0.0

      - name: Generate SBOM
        uses: CycloneDX/gh-gomod-generate-sbom@efc74245d6802c8cefd925620515442756c70d8f # v2.0.0
        with:
          version: v1
          # added assert-licenses as required by dependency-track
          args: mod -licenses -assert-licenses -output sources_${{ matrix.goos }}_${{ matrix.goarch }}.sbom.xml
        env:
          GOARCH: ${{ matrix.goarch }}
          GOOS: ${{ matrix.goos }}

      - name: Generate LICENSES.md and evaluate licenses
        if: ${{ matrix.goarch == 'amd64' && matrix.goos == 'linux' }}
        uses: mvdkleijn/licenses-action@6a6e38196451b10d8e263745301ecd660cf45035 # v1.2.3
        with:
          # We only use the linux_amd64 variant here for generating the LICENSES.md
          sbom: sources_linux_amd64.sbom.xml
          type: xml
          filename: LICENSES.md
          evaluate: true
          template: |
            # Licenses
 
            The following third-party licenses are applicable to this project:
  
            {{range .SortedKeys}}## {{.}}
  
            {{range index $.ComponentsByLicense .}}- {{.Name}} ({{.Version}})
            {{end}}
            {{end}}
  
      - name: Add SBOM and LICENSES.md to release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          files: |
            sources_${{ matrix.goos }}_${{ matrix.goarch }}.sbom.xml
            LICENSES.md
