name: Check licenses and compatibility on PR
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  sbom:
    name: Generate SBOM and evaluate licenses
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.0.0

      - name: Generate SBOM
        uses: CycloneDX/gh-gomod-generate-sbom@efc74245d6802c8cefd925620515442756c70d8f # v2.0.0
        with:
          version: v1
          # added assert-licenses as required by dependency-track
          args: mod -licenses -assert-licenses -output sources_linux_amd64.sbom.xml

      - name: Evaluate license compatibility
        uses: mvdkleijn/licenses-action@6a6e38196451b10d8e263745301ecd660cf45035 # v1.2.3
        with:
          # We only use the linux_amd64 variant here for generating the LICENSES.md
          sbom: sources_linux_amd64.sbom.xml
          type: xml
          filename: tmp-LICENSES.md
          evaluate: true
          template: |
            # Licenses
 
            The following third-party licenses are applicable to this project:
  
            {{range .SortedKeys}}## {{.}}
  
            {{range index $.ComponentsByLicense .}}- {{.Name}} ({{.Version}})
            {{end}}
            {{end}}
  