name: Build and release OLM bundle
on:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  contents: write
  packages: write

jobs:
  build-and-push-olm-bundle:
    name: Generate, validate, and publish OLM bundle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: '1.25'

      - name: Install dependencies (operator-sdk, kustomize)
        run: |
          make operator-sdk
          make kustomize

      - name: Generate OLM bundle
        run: make bundle VERSION=${{ github.ref_name }} CHANNELS=stable DEFAULT_CHANNEL=stable

      - name: Validate OLM bundle
        run: make bundle-validate

      - name: Build and push OLM bundle image
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          make bundle-build VERSION=${VERSION}
          make bundle-push VERSION=${VERSION}

      - name: Add bundle manifests to release assets
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2.4.1
        with:
          files: |
            bundle/metadata/annotations.yaml
            bundle/manifests/*
